local ls = require 'luasnip'
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node
local c = ls.choice_node

return {
  -- personal enviroments
  s('mpar', {
    t '\\begin{mypar}',
    t { '', '\t' },
    i(1),
    t { '', '\\end{mypar}' },
  }),

  s('thm', {
    t '\\begin{thm}',
    c(1, {
      t '', -- no optional argument
      t '[theorem]',
      t '[lemma]',
      t '[proposition]',
      t '[corollary]',
      t '[definition]',
    }),
    t '{',
    i(2, 'Statement'),
    t '}',
    t { '', '\t' },
    i(3),
    t { '', '\\end{thm}' },
  }),

  s('proof', {
    t '\\begin{proof}',
    t { '', '\t' },
    i(1),
    t { '', '\\end{proof}' },
  }),

  s('subproof', {
    t '\\begin{subproof}',
    t { '', '\t' },
    i(1),
    t { '', '\\end{subproof}' },
  }),

  -- personal commands
  s('sh', {
    t '\\sh{',
    i(1, 'sub heading'),
    t '}',
    i(0),
  }),

  -- useful general enviroments
  s('sec', {
    t '\\section{',
    i(1, 'title'),
    t { '}', '' },
    t '\\begin{mypar}',
    t { '', '\t' },
    i(0),
    t { '', '\\end{mypar}' },
  }),

  s('aln', {
    t { '\\begin{align*}' },
    t { '', '    ' }, i(1), t { ' &= ' }, i(2), t { ' \\\\' },
    t { '', '    &= ' }, i(0),
    t { '', '\\end{align*}' }
  }),

  s('[]', {
    t { '\\[' },
    t { '', '    ' }, i(0),
    t { '', '\\]' }
  }),

  s('fig', {
    t '\\begin{figure}[',
    c(1, { t 'h', t 't', t 'b', t 'H' }),
    t ']',
    t { '', '\t\\centering' },
    t { '', '\t\\includegraphics[width=' },
    i(2, '0.8'),
    t '\\textwidth]{',
    i(3, 'filename'),
    t '}',
    t { '', '\t\\caption{' },
    i(4, 'caption'),
    t '}',
    t { '', '\t\\label{fig:' },
    i(5, 'label'),
    t '}',
    t { '', '\\end{figure}' },
  }),

  s('item', {
    t '\\begin{itemize}',
    t { '', '\t\\item ' },
    i(1),
    t { '', '\\end{itemize}' },
  }),

  s('enum', {
    t '\\begin{enumerate}',
    t { '', '\t\\item ' },
    i(1),
    t { '', '\\end{enumerate}' },
  }),

  -- personal typesetting
  s('meta', {
    t '\\documentclass{article}',
    t { '', '\\usepackage{amsmath}' },
    t { '', '\\usepackage{amsthm}' },
    t { '', '\\usepackage{amssymb}' },
    t { '', '\\usepackage{graphicx}' },
    t { '', '\\usepackage{hyperref}' },
    t { '', '\\usepackage{enumitem}' },
    t { '', '\\usepackage{geometry}' },
    t { '', '\\usepackage{calligra}' },
    t { '', '\\usepackage{mathpazo}' },
    t { '', '\\usepackage{tikz}' },
    t { '', '\\usepackage{changepage}' },
    t { '', '\\usepackage{microtype}' },
    t { '', '\\usepackage{nicefrac}' },
    t { '', '\\usepackage{forest}' },
    t { '', '\\usepackage{xcolor}' },
    t { '', '\\usepackage{ifthen}' },
    t { '', '' },
    t { '', '% ==========================' },
    t { '', '% ========== meta ==========' },
    t { '', '' },
    t { '', '\\title{' },
    i(1, 'new document'),
    t '}',
    t { '', '\\author{' },
    i(2, 'mrdandelion6'),
    t '}',
    t { '', '\\date{' },
    i(3, 'September 2025'),
    t '}',
    t { '', '' },
    t { '', '% === link colors ===' },
    t { '', '\\hypersetup{' },
    t { '', '    colorlinks=true,' },
    t { '', '    linkcolor=blue,' },
    t { '', '    urlcolor=blue,' },
    t { '', '}' },
    t { '', '% ===' },
    t { '', '' },
    t { '', '% === commands ===' },
    t { '', '\\newcommand{\\sh}[1]{\\par\vspace{0.2cm}{\\fontsize{10.5}{14}\\selectfont\\bfseries #1}\\par}' },
    t { '', '% ===' },
    t { '', '' },
    t { '', '% === par indentations ===' },
    t { '', '\\newenvironment{mypar}{%' },
    t { '', '    \\setlength{\\parskip}{1em}%' },
    t { '', '    \\parindent=0pt%' },
    t { '', '}{%' },
    t { '', '    \\par%' },
    t { '', '}' },
    t { '', '% ===' },
    t { '', '' },
    t { '', '% === section indentations ===' },
    t { '', '\\makeatletter' },
    t { '', '\\renewcommand\\section{\\@startsection {section}{1}{\\z@}%' },
    t { '', '    {-5ex \\@plus -1ex \\@minus -.2ex}% above' },
    t { '', '    {1ex \\@plus .2ex}% below' },
    t { '', '{\\normalfont\\large\\bfseries}}%' },
    t { '', '\\makeatother' },
    t { '', '% ===' },
    t { '', '' },
    t { '', '% === custom indentation ===' },
    t { '', '\\newenvironment{cindent}[1]{%' },
    t { '', '    \\par% start a new paragraph' },
    t { '', '    \\setlength{\\leftskip}{#1}% set the left indentation' },
    t { '', '    \\noindent% no paragraph indentation' },
    t { '', '    \\ignorespaces% ignore spaces after \\begin{customindent}' },
    t { '', '}{%' },
    t { '', '    \\par% end the paragraph' },
    t { '', '}' },
    t { '', '% ===' },
    t { '', '' },
    t { '', '% === proof ===' },
    t { '', '\\renewenvironment{proof}[1][]{\\noindent{\\textit{Proof%' },
    t { '', '    \\if\\relax\\detokenize{#1}\\relax\\else\\ \\textnormal{#1}\\fi.}}\\\\' },
    t { '', '    \\begin{cindent}{0.5cm}' },
    t { '', '        \\vspace{-0.6cm}' },
    t { '', '' },
    t { '', '    \\vspace{-0.5cm}}' },
    t { '', '{\\end{cindent}\\hfill$\\square$}' },
    t { '', '' },
    t { '', '\\newenvironment{subproof}[1][]{\\noindent{\\textit{subproof%' },
    t { '', '    \\if\\relax\\detokenize{#1}\\relax\\else\\ \\textnormal{#1}\\fi.}}\\\\' },
    t { '', '    \\begin{cindent}{0.5cm}' },
    t { '', '' },
    t { '', '    \\vspace{-0.5cm}}' },
    t { '', '{\\end{cindent}\\hfill$\\blacksquare$}' },
    t { '', '% ===' },
    t { '', '' },
    t { '', '% === thm ===' },
    t { '', '\\newenvironment{thm}[2][\\unskip]{%' },
    t { '', '    \\vspace{0.2cm}' },
    t { '', '    \\noindent{\\textbf{#1} \\ifthenelse{\\equal{#2}{\\unskip}}{}{#2}}% check if the second argument is provided' },
    t { '', '    \\begin{cindent}{0.5cm}' },
    t { '', '        \\vspace{-0.6cm}' },
    t { '', '' },
    t { '', '    \\vspace{-0.5cm}}' },
    t { '', '{\\end{cindent}\\hfill$\\blacklozenge$}' },
    t { '', '% ===' },
    t { '', '' },
    t { '', '% === tikz ===' },
    t { '', '\\tikzset{' },
    t { '', '    every child/.style={' },
    t { '', '        edge from parent/.style={draw, ->}' },
    t { '', '    }' },
    t { '', '}' },
    t { '', '% ===' },
    t { '', '' },
    t { '', '% === other separation ===' },
    t { '', '\\setlist[itemize]{topsep=0.2em}' },
    t { '', '% ===' },
    t { '', '' },
    t { '', '% ========== meta ==========' },
    t { '', '% ==========================' },
    t { '', '' },
    t { '', '\\begin{document}' },
    t { '', '' },
    t { '', '\\maketitle' },
    t { '', '' },
    i(0),
    t { '', '' },
    t { '', '\\end{document}' },
  }),
}
